spring:
  application:
    name: ecom-book-service
  datasource:
    url: jdbc:mysql://database.amazonaws.com/ecomdb
    username: admin
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
