spring:
  application:
    name: ecom-book-service
  datasource:
    url: jdbc:mysql://database-1.ci7jwbjemnqv.ap-south-1.rds.amazonaws.com/ecomdb
    username: admin
    password: 9848MydbAsh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
