spring:
  application:
    name: ecom-user-service
  datasource:
    url: jdbc:mysql://database-1.ci7jwbjemnqv.ap-south-1.rds.amazonaws.com/ecomdb
    username: admin
    password: 9848MydbAsh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: false

server:
  port: 8082