spring:
  application:
    name: ecom-user-service
  datasource:
    url: jdbc:mysql://database-amazonaws.com/ecomdb
    username: admin
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: false

server:
  port: 8082
